techtitansdev/softdev

src/server/api/routers/fundraiser.ts, src/server/api/routers/tests/fundraiser.test.ts
This PR includes the Get By Id procedure for specific fundraiser with Unit test.
=> test(fundraiser.ts, fundraiser.test.ts): added getById procedure with unit test

src/pages/admin/projects/edit/[id]/index.tsx
This PR includes: 
- Fixed image not appearing on load
- Fixed remove image button not appearing
- Fixed about editor (now accepts changes)
- Fixed about editor (now saves changes to the database)
Remaining Issues:
- Cloudinary delete
=> [fix] Edit Project

package-lock.json, package.json, src/pages/admin/projects/components/__tests__/ProjectCard.integration.test.tsx
This PR includes the integration testing for delete project feature.
=> test(projectcard.integration.test.tsx)

src/pages/admin/funding/components/__test__/createFunding.test.tsx
=> test(create testing): added testing for create funding

src/pages/admin/projects/__test__/projects/index.test.tsx, src/pages/admin/projects/components/ProjectCard.tsx
- Tests if code renders project cards properly
- Tests if code renders project images correctly
=> [test] View Collection of Projects

src/pages/admin/blogs/components/BlogCard.tsx, src/pages/admin/blogs/index.tsx
the pr includes
- blog collection view
- delete blog
=> feat(blog collection view/delete): added blog collection view and delete

prisma/schema.prisma, src/server/api/routers/milestone.ts
- Added a description column for milestones
- Changed name column to milestone column
=> [Fix] Project MIlestone

src/pages/projects/__tests__/ViewProject.test.tsx
This PR includes unit test file for Project Page view.
=> test(viewproject.test.tsx)

prisma/schema.prisma, src/server/api/routers/milestone.ts
- Changed relationship of milestone from project to fundraiser
=> [Refactor] Project Milestone

src/server/api/routers/milestone.ts, src/server/api/routers/tests/fundraiser.test.ts, src/server/api/routers/tests/milestone.test.ts, src/server/api/routers/tests/project.test.ts, src/server/api/trpc.ts
- Unit test for create milestone
- Unit test for get all milestones of a fundraiser
- Fixes for fundraiser.test.ts
- Fixes for project.test.ts
=> [test] Milestones

src/server/api/routers/tests/fundraiser.test.ts
This PR includes unit test file for Delete fundraiser procedure.
=> test(fundraiser.test.ts)

src/server/api/routers/categories.ts, src/server/api/routers/tests/category.test.ts
- Unit test for create category procedure
=> [Test] Create Category

package.json, prisma/schema.prisma, prisma/seed.ts, src/pages/admin/projects/create.tsx, src/pages/admin/projects/edit/[id]/index.tsx, src/server/api/root.ts, src/server/api/routers/categories.ts
- [ √]  Added the create category feature
- [ √] Modified the Edit for the create category feature
- [ √] Modified the schema category to fit the added feature
- [ √] modified the create category
- [ √] create seed file for the category optiop
-  [ √] modified package.json for the seed, 
- note: to seed the data run  (npx prisma db seed)
- [ √] modified the category api
=> feat(create category): added the feature for the create category

src/pages/admin/blogs/__tests__/BlogCollectionView.test.tsx, src/pages/admin/blogs/components/BlogCard.tsx
This PR includes unit test frontend for the Collection of Blogs View.
=> test(blogcollectionview.test.tsx)

src/pages/admin/blogs/__tests__/SelectFeaturedBlogs.integration.test.tsx, src/pages/admin/blogs/__tests__/SelectFeaturedBlogs.test.tsx
This PR includes unit and integration tests for the Select Featured Blogs feature.
UNIT TEST
INTEGRATION TEST
=> Test/admin/select featured/blogs

prisma/schema.prisma, src/server/api/routers/feedback.ts
- modifications to the schema to include an entity for feedback
- protected procedure for creating a new feedback
- protected procedure for getting all feedback
=> [Feat] Leave Feedback

src/pages/admin/comments/__tests__/ViewComments.test.tsx
This PR includes unit test for frontend of View Comments feature.
=> test(viewcomments.test.tsx)

src/pages/blogs/__tests__/ViewBlogPage.test.tsx
This PR includes unit test for View Blog Page feature.
=> test(viewblogpage.test.tsx): added unit test for view blog page feature

src/pages/blogs/test/blogView.test.tsx
=> test(blog view): added test for blog view

src/pages/funded-projects/[id]/payment.tsx, src/pages/funded-projects/__tests__/DonationType.integration.test.tsx
This PR includes integration test for Donation Type feature.
=> test(donationtype.integration.test.tsx)

src/pages/funded-projects/__tests__/DonationType.test.tsx
This PR includes unit test for Donation Type feature.
=> test(donationtype.test.tsx): added unit test for frontend of donation type feature

src/server/api/routers/feedback.ts, src/server/api/routers/tests/feedback.test.ts
- a procedure for getting all feedback given a project Id
- unit test for creating a new feedback
- unit test for getting all feedback given a project id
=> [Test] Feedback Procedures

src/middleware.ts, src/server/api/routers/funding.ts, src/server/api/routers/tests/funding.test.ts
This PR include:
- Donations router
- Procedure to record donations done to each fundraiser
- Procedure to view recorded donations for each fundraiser
- Tests for each procedures
=> [Feat] Record Donations

src/pages/admin/blogs/__tests__/BlogSpecificView.integration.test.tsx
=> refactor(blog specific view test): modified the code

src/pages/admin/projects/__test__/AboutProject.test.tsx
=> test(about project editor): test the about project editor

prisma/schema.prisma, src/components/filter/FilterByCommentProjectName.tsx, src/pages/admin/comments/index.tsx, src/server/api/root.ts, src/server/api/routers/feedback.ts, src/types/Feedback.ts
- Backend and front end integration of view feedback and filter
- changes to the schema to include "created" for the feedback table
- changes to the getAll procedure of the feedback to return the proper format
=> [Feat] View Feedback

src/pages/admin/donors/index.tsx, src/server/api/root.ts, src/server/api/routers/funding.ts
- connecting the backend and front end view donors
=> [Feat] View Donors

prisma/schema.prisma, src/pages/admin/donors/index.tsx, src/server/api/routers/funding.ts
- modifications to the schema (donors and funding table)
- modifications to the funding router
- modifications to the view donors front end
=> [Refactor] View Donors

src/components/Sidebar.tsx
=> feat(admin signout): added sign out in sider bar

src/pages/admin/funding/index.tsx, src/pages/admin/projects/index.tsx
-Fix search in admin project and funding bug
=> fix(search): fix search bug on admin project and funding

prisma/schema.prisma, src/pages/admin/donors/index.tsx, src/server/api/routers/donors.ts, src/server/api/routers/funding.ts
- Added donatedAs to the schema and related routers
=> [Fix] View Donor

src/pages/admin/funding/components/MilestoneComponent.tsx
- added / fixed dates in milestone view
=> [Fix] Milestone Date

package-lock.json, prisma/schema.prisma, src/pages/admin/funding/components/MilestoneTable.tsx, src/pages/admin/funding/create.tsx, src/pages/admin/funding/edit/[id]/index.tsx, src/server/api/routers/milestone.ts
- added a date and status column in the milestones table
=> [Feat] Date and Status Column for Milestones

.github/workflows/production.yml, package-lock.json, package.json
- Added NEXTAUTH_URL to production.yml file for CI/CD pipeline issues.
=> fix(production.yml): added NEXTAUTH_URL to CI/CD pipeline to resolve build error

src/components/OtpVerification.tsx, src/pages/register/RegisterForm.tsx, src/server/api/routers/user.ts
The user data will only be sent to database after successful verification
=> fix(registration flow): fix the registration flow

src/pages/admin/funding/edit/[id]/index.tsx
Fix missed code on edit fundraiser
=> fix(edit-fundraiser): fix missing project objective description

src/pages/admin/funding/components/MilestoneComponent.tsx, src/pages/funded-projects/[id]/index.tsx, src/pages/funded-projects/components/SpecificAboutComponent.tsx
=> fix(fundraiser): fix ui for fundraiser milestone and about in mb view

src/pages/api/sendEmailReceipt.ts, src/pages/funded-projects/[id]/payment.tsx, src/utils/SendEmailPayment.ts
- automated email for payment confirmation
=> [feat] Payment Confirmation

src/components/AddAdminModal.tsx, src/pages/admin/administrator/index.tsx, src/pages/admin/index.tsx
=> fix(fix build-errror): fix build error

src/components/Sidebar.tsx
=> refactor(administrator): changed administrator icon

src/pages/admin/blogs/create.tsx, src/pages/admin/projects/create.tsx, src/pages/admin/projects/edit/[id]/index.tsx, src/server/api/routers/project.ts
- prevent default for remove blog image
- prevent default for remove project image
=> [Fix] Remove Image Reload Bug

src/pages/admin/blogs/edit/[id].tsx
this PR includes:
-fixes for blog reload bug
=> fix: reload bug

src/pages/admin/blogs/create.tsx, src/pages/admin/blogs/edit/[id].tsx, src/pages/admin/funding/create.tsx, src/pages/admin/projects/create.tsx, src/pages/admin/projects/edit/[id]/index.tsx
Fix layout for admin create and edit to be more understandable
=> feat(layout): fix layout for admin create and edit

src/pages/funded-projects/[id]/payment.tsx
=> [fix] Anonymous Payment
